server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafe
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true